title: 左一博客
avatar: https://spumetime-blog.oss-cn-shenzhen.aliyuncs.com/img/20250610005819525.jpg
favicon: https://spumetime-blog.oss-cn-shenzhen.aliyuncs.com/img/20250610005819525.jpg
# subtitle: # subtitle 已移至主题配置中
# 多语言
language:
  - zh-CN
  - en